// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
)

// KafkaReaderClient is an autogenerated mock type for the KafkaReaderClient type
type KafkaReaderClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *KafkaReaderClient) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommitMessages provides a mock function with given fields: ctx, msgs
func (_m *KafkaReaderClient) CommitMessages(ctx context.Context, msgs ...kafka.Message) error {
	_va := make([]interface{}, len(msgs))
	for _i := range msgs {
		_va[_i] = msgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...kafka.Message) error); ok {
		r0 = rf(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchMessage provides a mock function with given fields: ctx
func (_m *KafkaReaderClient) FetchMessage(ctx context.Context) (kafka.Message, error) {
	ret := _m.Called(ctx)

	var r0 kafka.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (kafka.Message, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) kafka.Message); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(kafka.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewKafkaReaderClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewKafkaReaderClient creates a new instance of KafkaReaderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKafkaReaderClient(t mockConstructorTestingTNewKafkaReaderClient) *KafkaReaderClient {
	mock := &KafkaReaderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
