// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
)

// KafkaWriterClient is an autogenerated mock type for the KafkaWriterClient type
type KafkaWriterClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *KafkaWriterClient) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteMessages provides a mock function with given fields: ctx, msgs
func (_m *KafkaWriterClient) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	_va := make([]interface{}, len(msgs))
	for _i := range msgs {
		_va[_i] = msgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...kafka.Message) error); ok {
		r0 = rf(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewKafkaWriterClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewKafkaWriterClient creates a new instance of KafkaWriterClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKafkaWriterClient(t mockConstructorTestingTNewKafkaWriterClient) *KafkaWriterClient {
	mock := &KafkaWriterClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
