name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true
      - run: |
          go install github.com/vektra/mockery/v2@v2.20.2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ghcr.io/pecigonzalo/kafka-canary
          tags: |
            type=semver,pattern={{version}}

      - name: Update Chart.yaml
        run: |
          yq eval '.version="${{ steps.meta.outputs.version }}"' -i ./charts/kafka-canary/Chart.yaml
          yq eval '.appVersion="${{ steps.meta.outputs.version }}"' -i ./charts/kafka-canary/Chart.yaml

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm chart to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/pecigonzalo/charts --username ${{ github.repository_owner }} --password-stdin
          helm package charts/kafka-canary
          helm push kafka-canary-${{ steps.meta.outputs.version }}.tgz oci://ghcr.io/pecigonzalo/charts
          rm kafka-canary-${{ steps.meta.outputs.version }}.tgz
